config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root                         'static_pages#home'
  get 'home'                => 'static_pages#home'
  get 'signup'              => 'users#signup'
  get 'search'              => 'recipes#search'
  post 'search'             => 'recipes#search'
  resources :ingredients
  resources :recipes
  resources :static_pages do
    get :autocomplete_ingredient_name, :on => :collection
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  autocomplete :ingredient, :name
  def home
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>

<div class="section no-pad-bot" id="index-banner">
  <div class="container">
    <div class="row center">
      <h2 class="header orange-text">This is the RandomFood project.</h2>
      <h5 class="header col s12 light">A nice way to find out what to eat today.</h5>
    </div>
  </div>
</div>

<div class="row center">
  <h3 class="header col s12 light">Search recipes with your <span class="enlighted-text">sh*ts</span> here.</h5>
  <div class="container">
    <!-- When submit the form, the view rendered will be the index view of our articles resource -->
    <%= form_tag(search_path, :method => 'get') do %>
      <div class="form-group">
        <%= autocomplete_field_tag 'search', '', autocomplete_ingredient_name_static_pages_path, 'data-delimiter' => ', ', :multiple => true, class: "form-control", placeholder: "Ingredients list" %>
        <%= submit_tag "Search!", class: "btn-large waves-effect waves-light orange"%>
      </div>
    <% end %>
  </div>
</div>