config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root                         'static_pages#home'
  get 'home'                => 'static_pages#home'
  get 'signup'              => 'users#signup'
  get 'search'              => 'recipes#search'
  post 'search'             => 'recipes#search'
  resources :ingredients
  resources :recipes
  resources :static_pages do
    get :autocomplete_ingredient_name, :on => :collection
  end

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  has_many :links
  has_many :ingredients, through: :links

  # Get all recipes that contains every ingredient of the ingredients list
  def self.get_recipes_from_ingredients ingredients

    results = Array.new
    unless ingredients.empty?
      ingredients.each do |ing|
        recipes = Recipe.joins(:ingredients).where(:ingredients => {:id => ing.id})
        if results.empty?
          results = recipes
        else
          results &= recipes
        end
      end
    end
    return results

  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index, :search]
  before_action :check_auth, only: [:create, :edit, :update, :destroy]

  #before_filter do
  #redirect_to home_url unless current_user && current_user.admin?
  #end

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
  end

  def search
    @ingredients = Ingredient.get_ingredients_from_search_string(params[:search])
    @recipes = Recipe.get_recipes_from_ingredients @ingredients
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create   
    ingredients = Ingredient.get_ingredients_from_recipe_creation_ingredients_list_string(params[:new_recipe_ingredients_list])
    @recipe = Recipe.new(recipe_params)

    ingredients.each do |ing|
      @recipe.ingredients << ing
    end

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.includes(:ingredients).find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def recipe_params
    params.require(:recipe).permit(:name)
  end

  def check_auth
    if  not current_user.admin?
      flash[:notice] = "Sorry, you need to be admin to play with recipes"
      redirect_to recipes_path
    end
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3 text-center">
    <%= form_for(@recipe) do |f| %>
      <% if @recipe.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

          <ul>
            <% @recipe.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.text_field :name, autofocus: true, class: "form-control", placeholder: :name %>
      </div>
      <div class="form-group">
        <%= autocomplete_field_tag 'new_recipe_ingredients_list', '', autocomplete_ingredient_name_static_pages_path, 'data-delimiter' => ', ', :multiple => true, class: "form-control", placeholder: "Ingredients list" %>
      </div>
      <div class="actions">
        <%= f.submit class: "btn waves-effect waves-light orange"%>
        <br><br><br><br>
        <%= link_to "Back", recipes_path, class: "btn waves-effect waves-light orange" %>
        <br><br><br><br>
      </div>
    <% end %>
  </div>
</div>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form' %>

<%= link_to "Show", @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<p id="notice"><%= notice %></p>

<div class="fixed-action-btn">
  <a href="<%= new_recipe_path %>" class="btn-floating btn-large orange">
    <i class="material-icons">add</i>
  </a>
</div>

<div class="section no-pad-bot" id="index-banner">
  <div class="container">
    <h2 class="header center orange-text">Listing Recipes</h2>
  </div>
</div>
<div class="row">

  <% @recipes.each do |recipe| %>  
    <div class="col s12 m4">

      <div class="card grey lighten-4">  
        <div class="card-content">
          <span class="card-title truncate"><%= recipe.name %></span>
        </div>

        <div class="card-action">
          <a><%= link_to 'Show', recipe %></a>
          <a><%= link_to 'Edit', edit_recipe_path(recipe) %></a>
          <a><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></a>
        </div>
      </div>
    </div>
  <% end %> 

</div>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form' %>

app/views/recipes/search.html.erb
<p id="notice"><%= notice %></p>

<h1>Results</h1>

<h4>Your shits : </h4>
<ul>
  <% @ingredients.each do |ingredient| %>
    <li><%= ingredient.name %></li>
  <% end %>
</ul>

<!-- Export this in helper -->
<% recipes_string = @recipes.count > 1 ? 'recipes' : 'recipe' %>

<h4>Our <%=@recipes.count %> awesome <%= recipes_string %> : </h4>
<ul>
  <% @recipes.each do |recipe| %>
    <li><%= link_to recipe.name, recipe %></li>
  <% end %>
</ul>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
<h4 class="orange-text">Name</h4>
<%= @recipe.name %>
</p>

<p>
<h4 class="orange-text">Ingredients</h4>
<% @recipe.ingredients.each do |ingredient| %>
  <div class="chip"><%= link_to ingredient.name, ingredient %> </div>
<% end %>
</p>

<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', :back %>