config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root                         'static_pages#home'
  get 'home'                => 'static_pages#home'
  get 'signup'              => 'users#signup'
  get 'search'              => 'recipes#search'
  post 'search'             => 'recipes#search'
  resources :ingredients
  resources :recipes
  resources :static_pages do
    get :autocomplete_ingredient_name, :on => :collection
  end

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_many :links
  has_many :recipes, through: :links

  # The search separator string that separate the ingredients in the search string
  SEARCH_SEPARATOR = ','
  # The where clause on name field
  INGREDIENT_NAME_WHERE_CLAUSE = 'lower(name) = ?'

  # Gets ingredients array from an ingredients search string
  def self.get_ingredients_from_search_string search_string

    results = Array.new
    unless search_string.nil?
      ing_strings = search_string.split(SEARCH_SEPARATOR)

      ing_strings.each do |ing_string|
        ingredient = Ingredient.where(INGREDIENT_NAME_WHERE_CLAUSE, ing_string.downcase.strip).first
        unless ingredient.nil?
          results << ingredient
        end
      end
    end

    return results
  end


  #Gets ingredients array from an ingredients list string, creating Ingredient object for each one that does not exist yet
  def self.get_ingredients_from_recipe_creation_ingredients_list_string ingredients_list_string

    results = Array.new
    unless ingredients_list_string.nil?
      ing_strings = ingredients_list_string.split(SEARCH_SEPARATOR)

      ing_strings.each do |ing_string|
        #Only if the given string is not empty / not equal to " " (happens when the last ingredient string is autocompleted with is name and ','
        unless (ing_string.length == 0 or ing_string == " ")
          #Check if the ingredient exist
          ingredient = Ingredient.where(INGREDIENT_NAME_WHERE_CLAUSE, ing_string.downcase.strip).first
            # If not, create it
            if ingredient.nil?
              ingredient = Ingredient.create(name: ing_string.downcase.strip)
            end
            results << ingredient
        end
      end
    end

    return results
  end

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index]
  before_filter :check_auth, only: [:create, :edit, :update, :destroy]

  #before_filter do
  #  redirect_to home_url unless current_user && current_user.admin?
  #end

  # GET /ingredients
  # GET /ingredients.json
  def index
    @ingredients = Ingredient.all
  end

  # GET /ingredients/1
  # GET /ingredients/1.json
  def show
  end

  # GET /ingredients/new
  def new
    @ingredient = Ingredient.new
  end

  # GET /ingredients/1/edit
  def edit
  end

  # POST /ingredients
  # POST /ingredients.json
  def create
    @ingredient = Ingredient.new(ingredient_params)

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully created.' }
        format.json { render :show, status: :created, location: @ingredient }
      else
        format.html { render :new }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingredients/1
  # PATCH/PUT /ingredients/1.json
  def update
    respond_to do |format|
      if @ingredient.update(ingredient_params)
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully updated.' }
        format.json { render :show, status: :ok, location: @ingredient }
      else
        format.html { render :edit }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    @ingredient.destroy
    respond_to do |format|
      format.html { redirect_to ingredients_url, notice: 'Ingredient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_ingredient
    @ingredient = Ingredient.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def ingredient_params
    params.require(:ingredient).permit(:name)
  end

  def check_auth
    if  not current_user.admin?
      flash[:notice] = "Sorry, you need to be admin to play with ingredients"
      redirect_to ingredients_path
    end
  end


end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/ingredients/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3 text-center">
    <%= form_for(@ingredient) do |f| %>
      <% if @ingredient.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

          <ul>
            <% @ingredient.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.text_field :name, autofocus: true, class: "form-control", placeholder: :name %>
      </div>
      <div class="actions">
        <%= f.submit class: "btn waves-effect waves-light orange"%>
        <br><br><br><br>
        <%= link_to "Back", ingredients_path, class: "btn waves-effect waves-light orange" %>
        <br><br><br><br>
      </div>
    <% end %>
  </div>
</div>

app/views/ingredients/edit.html.erb
<h1>Editing Ingredient</h1>

<%= render 'form' %>

<%= link_to 'Show', @ingredient %> |
<%= link_to 'Back', ingredients_path %>

app/views/ingredients/index.html.erb
<p id="notice"><%= notice %></p>

<div class="fixed-action-btn">
  <a href="<%=new_ingredient_path %>" class="btn-floating btn-large orange">
    <i class="material-icons">add</i>
  </a>
</div>

<div class="section no-pad-bot" id="index-banner">
  <div class="container">
    <h2 class="header center orange-text">Listing Ingredients</h2>
  </div>
</div>

<table class="striped">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ingredients.each do |ingredient| %>
      <tr>
        <td><%= ingredient.name %></td>
        <td><%= link_to 'Show', ingredient %></td>
        <td><%= link_to 'Edit', edit_ingredient_path(ingredient) %></td>
        <td><%= link_to 'Destroy', ingredient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/ingredients/new.html.erb
<h1>New Ingredient</h1>

<%= render 'form' %>

app/views/ingredients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
<strong>Name:</strong>
<%= @ingredient.name %>
</p>

<%= link_to 'Edit', edit_ingredient_path(@ingredient) %> |
<%= link_to 'Back', :back %>